# Generated by Django 5.1.5 on 2025-01-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_customer_is_active_customer_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
